import Head from 'next/head'
// import Image from 'next/image'
import tw, { styled } from 'twin.macro';
import { createClient } from '@supabase/supabase-js'
import { useState, useEffect } from 'react'
import { H1, Paragraph, Accent } from '../src/components/Typography';

const supabaseUrl = process.env.NEXT_PUBLIC_SUPABASE_URL ?? '';
const supabaseKey = process.env.NEXT_PUBLIC_SUPABASE_ANON_KEY ?? '';
const supabase = createClient(supabaseUrl, supabaseKey);

const Container = tw.div`flex justify-center items-center h-screen w-full text-center`;

const Heading = styled(H1)`
  ${tw`mb-2`}
`

export default function Home() {
  const [guests, setGuests] = useState<Models.Guest[]>([]);
  
  useEffect(() => {
    const getGuests = async () => {
      const { data } = await supabase.from('guests').select() as { data: Models.Guest[] };
      setGuests(data);
    };

    getGuests();
  }, [setGuests]);

  console.log('guests', guests);
  return (
    <Container>
      <Head>
        <title>Dorothy and Christopher&apos;s Wedding</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main>
        <Heading>Dorothy <Accent>&</Accent> Christopher</Heading>
        <Paragraph>Coming soon!</Paragraph>
      </main>
    </Container>
  )
}
