import Head from 'next/head'
import tw, { styled } from 'twin.macro';
import { useSpring, animated } from 'react-spring';
import { createClient } from '@supabase/supabase-js'
import { useState, useEffect } from 'react'
import { H1, Paragraph, Accent } from '../src/components/Typography';

// const supabaseUrl = process.env.NEXT_PUBLIC_SUPABASE_URL ?? '';
// const supabaseKey = process.env.NEXT_PUBLIC_SUPABASE_ANON_KEY ?? '';
// const supabase = createClient(supabaseUrl, supabaseKey);

const Container = tw.main`
  flex flex-col
  justify-center items-center
  h-screen w-full
  text-center
`;

const Heading = styled(animated(H1))`
  ${tw`mb-5`}
`
const P = styled(animated(Paragraph))``;

const Main = () => {
  const animatedHeading = useSpring({
    from: {
      y: -10,
      opacity: 0.05
    },
    to: {
      y: 0,
      opacity: 1
    },
    config: { duration: 750 },
  });
  const animmateParagraph = useSpring({
    from: {
      y: -25,
      opacity: 0.05
    },
    to: {
      y: 0,
      opacity: 1
    },
    config: { duration: 750 },
  });
  return (
    <Container>
      <Head>
        <title>Dorothy and Christopher&apos;s Wedding</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
        <Heading style={animatedHeading}>Dorothy <Accent>&</Accent> Christopher</Heading>
        <P style={animmateParagraph}>Coming soon!</P>
    </Container>
  )
}

export default Main;
