import Head from 'next/head'
import Image from 'next/image'
import styles from '../styles/Home.module.css'
import { createClient } from '@supabase/supabase-js'
import { useState, useEffect } from 'react'

const supabaseUrl = process.env.NEXT_PUBLIC_SUPABASE_URL ?? '';
const supabaseKey = process.env.NEXT_PUBLIC_SUPABASE_ANON_KEY ?? '';
const supabase = createClient(supabaseUrl, supabaseKey);



export default function Home() {
  const [guests, setGuests] = useState([]);
  
  useEffect(() => {
    const getGuests = async () => {
      const result: any = await supabase.from('guests').insert({
        first_name: 'Jimmy',
        last_name: 'Huynh',
        address_1: '255 S. Grand Ave',
        address_2: 'APT 2113',
        city: 'Los Angeles',
        state: 'CA',
        zip_code: '90012',
        is_attending: true,
        meal_preference: 'chicken',
      });
      setGuests(result.data);
    };

    getGuests();
  }, [setGuests]);

  console.log('guests', guests);
  return (
    <div className={styles.container}>
      <Head>
        <title>Dorothy and Christopher&apos;s Wedding</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className={styles.main}>
        DorothyAndChristopher.com is Under Construction!!
      </main>
    </div>
  )
}
