-- This script was generated by the Schema Diff utility in pgAdmin 4
-- For the circular dependencies, the order in which Schema Diff writes the objects is not very sophisticated
-- and may require manual changes to the script to ensure changes are applied in the correct order.
-- Please report an issue for any failure with the reproduction steps.

CREATE TABLE IF NOT EXISTS public.parties
(
    id bigint NOT NULL GENERATED BY DEFAULT AS IDENTITY ( INCREMENT 1 START 1 MINVALUE 1 MAXVALUE 9223372036854775807 CACHE 1 ),
    created_at timestamp with time zone NOT NULL DEFAULT now(),
    updated_at timestamp with time zone NOT NULL DEFAULT now(),
    size smallint NOT NULL,
    name text COLLATE pg_catalog."default",
    type text COLLATE pg_catalog."default",
    address text COLLATE pg_catalog."default",
    email text COLLATE pg_catalog."default",
    CONSTRAINT party_pkey PRIMARY KEY (id),
    CONSTRAINT parties_address_key UNIQUE (address),
    CONSTRAINT parties_email_key UNIQUE (email),
    CONSTRAINT parties_name_key UNIQUE (name)
)

TABLESPACE pg_default;

ALTER TABLE IF EXISTS public.parties
    OWNER to supabase_admin;

GRANT ALL ON TABLE public.parties TO anon;

GRANT ALL ON TABLE public.parties TO authenticated;

GRANT ALL ON TABLE public.parties TO postgres;

GRANT ALL ON TABLE public.parties TO service_role;

GRANT ALL ON TABLE public.parties TO supabase_admin;

CREATE TABLE IF NOT EXISTS public.guests
(
    id bigint NOT NULL GENERATED BY DEFAULT AS IDENTITY ( INCREMENT 1 START 1 MINVALUE 1 MAXVALUE 9223372036854775807 CACHE 1 ),
    created_at timestamp with time zone NOT NULL DEFAULT now(),
    updated_at timestamp with time zone NOT NULL DEFAULT now(),
    first_name text COLLATE pg_catalog."default" NOT NULL,
    last_name text COLLATE pg_catalog."default" NOT NULL,
    is_attending boolean,
    meal_preference text COLLATE pg_catalog."default",
    party_id bigint,
    CONSTRAINT guests_pkey PRIMARY KEY (id),
    CONSTRAINT guests_party_id_fkey FOREIGN KEY (party_id)
        REFERENCES public.parties (id) MATCH SIMPLE
        ON UPDATE NO ACTION
        ON DELETE NO ACTION
)

TABLESPACE pg_default;

ALTER TABLE IF EXISTS public.guests
    OWNER to supabase_admin;

GRANT ALL ON TABLE public.guests TO anon;

GRANT ALL ON TABLE public.guests TO authenticated;

GRANT ALL ON TABLE public.guests TO postgres;

GRANT ALL ON TABLE public.guests TO service_role;

GRANT ALL ON TABLE public.guests TO supabase_admin;
